[package]
name = "mogral"
version = "0.1.0"
edition = "2021"
authors = ["raii <raii.program@gmail.com>"]
license = "MIT OR Apache-2.0"

[build-dependencies]
lalrpop = "0.19.9"

[dependencies]
lalrpop-util = { version = "0.19.9", features = ["lexer"] }
regex = "1"
